name: pulse
description: "Pulse is a chat app built with flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.5.0
  equatable: ^2.0.5
  shared_preferences: ^2.5.2
  dio: ^5.7.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  pretty_dio_logger: ^1.4.0
  dart_either: ^2.0.0
  get_it: ^8.0.3
  intl: ^0.19.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  uuid: ^3.0.7
  fluttertoast: ^8.2.12
  google_sign_in: ^6.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
flutter_intl:
  enabled: true