// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGKBv6y78d5s7U1660oZv-5122bVOfd74',
    appId: '1:1060992679796:web:e94fbcbeb62b81bef27621',
    messagingSenderId: '1060992679796',
    projectId: 'flutter-chat-8d927',
    authDomain: 'flutter-chat-8d927.firebaseapp.com',
    storageBucket: 'flutter-chat-8d927.firebasestorage.app',
    measurementId: 'G-H90N98PBWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOnR-oI67ByvVt7oObAS0JPzghG_SrVwg',
    appId: '1:1060992679796:android:9ad97d6db9d97904f27621',
    messagingSenderId: '1060992679796',
    projectId: 'flutter-chat-8d927',
    storageBucket: 'flutter-chat-8d927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8iQxliby3azbHPA1H4XTO5MeBkaOrVa8',
    appId: '1:1060992679796:ios:25b6b622b2bca0e9f27621',
    messagingSenderId: '1060992679796',
    projectId: 'flutter-chat-8d927',
    storageBucket: 'flutter-chat-8d927.firebasestorage.app',
    iosBundleId: 'com.example.pulse.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8iQxliby3azbHPA1H4XTO5MeBkaOrVa8',
    appId: '1:1060992679796:ios:25b6b622b2bca0e9f27621',
    messagingSenderId: '1060992679796',
    projectId: 'flutter-chat-8d927',
    storageBucket: 'flutter-chat-8d927.firebasestorage.app',
    iosBundleId: 'com.example.pulse.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGKBv6y78d5s7U1660oZv-5122bVOfd74',
    appId: '1:1060992679796:web:67fbb6ba5a3bde30f27621',
    messagingSenderId: '1060992679796',
    projectId: 'flutter-chat-8d927',
    authDomain: 'flutter-chat-8d927.firebaseapp.com',
    storageBucket: 'flutter-chat-8d927.firebasestorage.app',
    measurementId: 'G-M91T00V1XP',
  );
}
